### ISSUE TITLE
Have an error for plain text

### ISSUE THREAD

**Issue by kalombos** [jpuri/html-to-draftjs#11]
I am not sure is it a bug or a feature but the code below raises an error:

```
const html = 'some plain text without tags';
const blocksFromHTML = htmlToDraft(html);
const contentState = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks);
editorState = EditorState.createWithContent(contentState);
```

The error is:

> TypeError: t.blocks[r] is undefined

I think it would be great if the library can convert plain text into the editor state

@jpuri i can try to make a pull request if you point me on basic moments how to fix it.

**Comment by jpuri** [comment]
@kalombos: You can check methods here for conversion from raw test: https://draftjs.org/docs/api-reference-data-conversion.html

The lib does not supports this atm.

**Comment by pavel06081991** [comment]
@jpuri, I have the same problem. And we can not use any method from the link you gave. It seems html-to-draftjs must understand plain text.

**Comment by jpuri** [comment]
Release `html-to-draftjs@0.1.0-beta9` fixes the issue.
