### ISSUE TITLE
WARNING: DraftEntity.create will be deprecated soon! Please use "contentState.createEntity" instead.

### ISSUE THREAD

**Issue by vxzhong** [jpuri/html-to-draftjs#12]
WARNING: DraftEntity.create will be deprecated soon!
Please use "contentState.createEntity" instead.

When **htmlToDraft** is used, above warning is throwed.

**Comment by jpuri** [comment]
Thanks for reporting @vxzhong , I will soon fix.

**Comment by Toosick** [comment]
@jpuri Any word?

**Comment by DiroKate** [comment]
get the same problem

**Comment by jpuri** [comment]
I spent much time debugging this today, fix seems hard unless I plan some big and breaking changes. I will plan some time for this soon.

**Comment by jpuri** [comment]
I found a hack to fix it. Its good in latest release `0.1.0-beta11`

**Comment by Toosick** [comment]
@jpuri Cool deal thanks. I will be updating our project to include your NPM package again instead of my GitHub patch fork.
