### ISSUE TITLE
Image loses the data of alignment

### ISSUE THREAD

**Issue by denova** [jpuri/html-to-draftjs#21]
hi, @jpuri thanks for the awesome editor!

Seems this lib loses the img alignment data when creating draftjs state.

I think [there](https://github.com/jpuri/html-to-draftjs/blob/9cee3cfcdc3d27b3ea094215c6d1eda55a589d73/src/library/index.js#L47..L49) should be line like ```entityConfig.alignment=...```

What do you think?

**Comment by jpuri** [comment]
Looking into the issue now @denova

**Comment by jpuri** [comment]
Issue fixed in release `0.1.0-beta11`.

**Comment by denova** [comment]
thanks @jpuri !
