### ISSUE TITLE
Img src problem

### ISSUE THREAD

**Issue by Toosick** [jpuri/html-to-draftjs#22]
`entityConfig.src = node.src;` does not work when I am using images. I had to change it to `entityConfig.src = node.getAttribute('src');`. The src property is not up to date with the attributes property on the node. Does this have to be changed to getAttribute or am I doing something wrong?

**Comment by jpuri** [comment]
Hi @Toosick ,

One question, does using `getAttribute` fixes the issue for you ?

**Comment by Toosick** [comment]
Yes. If my pull request is sufficient let me know. If not, you can do it your way.

**Comment by lijax** [comment]
same here. `entityConfig.src = node.src||node.getAttribute('src');` this might be better.

**Comment by jpuri** [comment]
@Toosick , @lijax : sorry for the delay. I will check this issue and PR soon.

**Comment by jpuri** [comment]
PR is merged release `html-to-draftjs@0.1.0-beta9` has the changes. Thanks @Toosick , @lijax .
