### ISSUE TITLE
I got error TypeError: block.getData(...) is undefined 

### ISSUE THREAD

**Issue by kalombos** [jpuri/html-to-draftjs#3]
Here is the code:

```
import {EditorState, ContentState, convertToRaw} from 'draft-js'

import draftToHtml from 'draftjs-to-html';
import htmlToDraft from 'html-to-draftjs';


const contentBlock = htmlToDraft('<p></p>');
const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
const outputEditorState = EditorState.createWithContent(contentState);


const rawContent = convertToRaw(outputEditorState.getCurrentContent());
const html = draftToHtml(rawContent);
console.log(html, 'html');
```

Is it possible to avoid the error? I used such html code because previously i saved converted empty state to database and after that i wanted to edit the html but i got the error.

**Comment by jpuri** [comment]
@kalombos let me check. Also one thing I would strongly recommend to use JSON format for saving in DB. And convert JSON to html for just display.

**Comment by jpuri** [comment]
Just released `0.1.0-beta3` with the fix.

**Comment by kalombos** [comment]
Working for me, thank you. Also i have an error when i try to load custom html which was not created by the editor. Maybe it would be better just ignore unknown tags instead of raising exceptions like it works for draft-convert library. I can provide the html if you need it.

**Comment by ZeroCho** [comment]
I still have similar error
![image](https://cloud.githubusercontent.com/assets/10962668/22624747/a4970cca-ebc8-11e6-80f9-58833ce8f213.png)

The html code I used is 100% from **react-draft-wysiwyg**

my code is
```
const contentState = ContentState.createFromBlockArray(htmlToDraft(e.target.value)).contentBlocks);
return convertToRaw(contentState);
```
`e.target.value` is html string.

**Comment by jpuri** [comment]
Hey @ZeroCho, can you plz share the html string also. I will check at my end.

**Comment by Amitom** [comment]
Hi @jpuri , I just cloned this project and only replaced the html constant string with : "<p><img src="https://avatars0.githubusercontent.com/u/2182307?v=3&s=460" /></p>"

Same error than @ZeroCho ;)

PS : A big thanks for this and the awesome wysiwyg

**Comment by jpuri** [comment]
Sorry guys I will check this soon.

**Comment by jpuri** [comment]
I just made this release `0.1.0-beta6` can you guys plz check if you still face the issue. I am keen to fix all issues and stabilize this repo for 1.0 release now.

**Comment by Amitom** [comment]
I just tried with the html of my previous comment, same thing :/

`convertFromDraftStateToRaw.js:43 Uncaught TypeError: block.getData(...).toObject is not a function`

**Comment by Amitom** [comment]
Can't see the beta6 but the issue still there with the HTML of my previous comment :/
`convertFromDraftStateToRaw.js:43 Uncaught TypeError: block.getData(...).toObject is not a function`

**Comment by jpuri** [comment]
![screen shot 2017-02-12 at 11 51 27 am](https://cloud.githubusercontent.com/assets/2182307/22860116/b78557e6-f119-11e6-9a85-123c9884560a.png)


Its there plz check.

**Comment by Amitom** [comment]
Works perfectly for me, you rocks !
