### ISSUE TITLE
Internal style property is ignored or Image not coming

### ISSUE THREAD

**Issue by NishargShah** [jpuri/html-to-draftjs#88]
Hello, I am working on my project and I used `react draft wysiwyg` and stored the `HTML` in my database, now I want to show the editor state from my HTML and I find many ways to convert it but my goal is to convert 

```
1. Raw HTML
2. Raw HTML inline styles
3. Image
```
those into editor state but I can't match all of the three criteria with my code, so can you suggest to me how to convert it, let me give you the example I tried.

In the below Code,

1. Raw HTML works fine
2. Raw HTML inline styles work fine
3. Image is not working

```javascript
import htmlToDraft from "html-to-draftjs";
import { ContentState, EditorState } from "draft-js";

const blocksFromHTML = htmlToDraft(data.notes);
const contentState = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap
);
const editorState = EditorState.createWithContent(contentState);
```

In the below Code,

1. Raw HTML works fine
2. Raw HTML inline styles not working
3. Image works fine

```javascript
import { ContentState, convertFromHTML, EditorState } from "draft-js";

const blocksFromHTML = convertFromHTML(data.notes);
const contentState = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap
);
const editorState = EditorState.createWithContent(contentState);
```

do you have a solution where all the above 3 will work fine??

**Comment by NishargShah** [comment]
I solved it by myself, Thanks !!

**Comment by slipenk** [comment]
Hello @NishargShah, how did you solve that?

**Comment by NishargShah** [comment]
I went with 1st solution that I described above and after I upgrade the library to the latest version, the image is also started working.
